### ISSUE TITLE
Errors on import

### ISSUE THREAD

**Issue by MrGadget1024** [MichalPetryka/LiteNetLib4Mirror#1]
Latest Mirror ([1701](https://github.com/vis2k/Mirror/releases/tag/master-1701)) & Unity 2018.3.6
Cloned your repo, copied in the LiteNetLib4Mirror folder and its meta into the Assets/Mirror/Transport folder.

![image](https://user-images.githubusercontent.com/9826063/53220376-32335380-3632-11e9-831a-b636c3a14a08.png)

**Comment by MichalPetryka** [comment]
@MrGadget1024 Should be fixed in 1.0.5
