### ISSUE TITLE
Unreliable channel can't send or receive any data

### ISSUE THREAD

**Issue by SkaiXu** [MichalPetryka/LiteNetLib4Mirror#11]
The unity version is 2018.3.9, LiteNetLib Version is 1.1.4
My channels are:
0 Reliable Ordered
1 Unreliable
2 reliable Unordered
3 reliable Unordered

I used the Unreliable to send the position sync. But nothing can be receive.Then I changed the Unreliable channel to Reliable Unordered. It worked. But it's is better to use unreliable channel.

**Comment by MichalPetryka** [comment]
Should be fixed in 1.1.5
