### ISSUE TITLE
UPnP Not Working

### ISSUE THREAD

**Issue by kraken22** [MichalPetryka/LiteNetLib4Mirror#12]
Hello,
UPnP is not working. I always get `Error -911: Internal Error.`
However, I have found a fix to the problem.
In `LiteNetLib4MirrorUtils.cs` in the `static async Task ForwardPortInternalAsync()`
```
Mapping mapping = new Mapping(networkProtocolType, ExternalIP ?? IPAddress.None, port, port, 0, ApplicationName);
```

is used to create the mapping that is passed to `await device.CreatePortMapAsync(mapping).ConfigureAwait(false);`
(i have extracted the mapping create out for debugging purposes.)

However a `new Mapping()` expects the InternalIP to be passed to it. 

For now, i have hard coded that and UPnP works perfectly.

However, to fix the bug completely we would need to find a way of getting the internal ip instead of the extenal ip. 

I hope this makes sense.

**Comment by kraken22** [comment]
something like this can find the local IP address

```
private static IPAddress LocalIPAddress() {
    if (!NetworkInterface.GetIsNetworkAvailable()) {
        return null;
    }

    IPHostEntry host = Dns.GetHostEntry(Dns.GetHostName());
    return host
        .AddressList
        .FirstOrDefault(ip => ip.AddressFamily == AddressFamily.InterNetwork);
}
```

**Comment by MichalPetryka** [comment]
Should be fixed
