### ISSUE TITLE
Client and server apps must have same `Application.productName` for auto-discovery to work

### ISSUE THREAD

**Issue by robinnorth** [MichalPetryka/LiteNetLib4Mirror#13]
As the Transport uses `Application.productName` as a means of validating whether an auto-discovery request should be processed, apps that have different product names will always fail discovery.

I found this out when testing two related client and server apps, one with 'Client' appended to the product name and the other with 'Server'. As you already have to provide a shared discovery key to validate an auto-discovery request, is this not a redundant restriction to place on apps, perhaps?

**Comment by MichalPetryka** [comment]
This is to prevent different software using the same networking library from trying to connect to each other, having the library take care of this is much more convenient and intuitive than doing it yourself.
Also, if you're using Mirror, two separate projects for client and server won't work properly

**Comment by robinnorth** [comment]
Thanks for your quick response @MichalPetryka! I agree, it's definitely intuitive to have the library take care of validation for you, I'm just wondering if you need to use both the product name and the discovery token to validate requests? If you do, then could the transport be configured to use a different shared string instead of the product name? 

I am building my client and server apps from the same project, but applying different product names at build time, so networking with Mirror is just fine, apart from this issue with auto-discovery.

**Comment by MichalPetryka** [comment]
Please make a PR adding a virtual method, that would return application name, but could be overrided and changed if you want.

**Comment by robinnorth** [comment]
Great, sure thing!
